import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { IconUsers } from '@tabler/icons-react';
import { adminApi, apiErrorMessage } from '@admin/api/adminApi';
import type { AccessSummary, AdminUserSummary } from '@admin/model/admin';
import { Alert } from '@shared/ui/Alert'; import { Badge } from '@shared/ui/Badge'; import { Button } from '@shared/ui/Button'; import { Card } from '@shared/ui/Card'; import { AdminPageHeader as PageHeader } from '@admin/pages/access/AdminPageHeader';

export function AccessPage() {
  const { t } = useTranslation(); const [users, setUsers] = useState<AdminUserSummary[]>([]); const [summary, setSummary] = useState<AccessSummary | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { void adminApi.users.summary().then((response) => setUsers(response.data)).catch((caught) => setError(apiErrorMessage(caught, t('common.error')))).finally(() => setLoading(false)); }, [t]);
  const open = async (id: number) => { setError(null); try { const response = await adminApi.access.summary(id); setSummary(response.data); } catch (caught) { setError(apiErrorMessage(caught, t('common.error'))); } };
  return <div className="space-y-6 p-6" data-testid="admin-protected-page"><PageHeader icon={IconUsers} iconTone="admin" title={t('admin.access.title')} subtitle={t('admin.access.subtitle')} actions={<div className="flex gap-3"><Link to="/roles">{t('admin.access.tabs.roles')}</Link><Link to="/access/governance">{t('admin.access.tabs.governance')}</Link></div>} />{error && <Alert variant="danger">{error}</Alert>}<Card>{loading ? <p>{t('common.loading')}</p> : <table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-start">{t('admin.access.members.name')}</th><th className="p-2 text-start">{t('admin.access.members.email')}</th><th className="p-2 text-end">{t('common.actions')}</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b"><td className="p-2">{user.name}</td><td className="p-2">{user.email}</td><td className="p-2 text-end"><Button size="sm" variant="secondary" onClick={() => void open(user.id)}>{t('admin.access.members.viewAccess')}</Button></td></tr>)}</tbody></table>}</Card>{summary && <Card><h2 className="mb-3 font-semibold">{t('admin.access.drawerTitle')}</h2><div className="mb-4 flex gap-2">{summary.functional_roles.map((role) => <Badge key={role} variant="accent">{role}</Badge>)}</div>{summary.scoped.map((row) => <div key={`${row.role}-${row.scope_type}-${row.scope_id}`} className="border-t py-3"><strong>{row.label}</strong><p>{row.scope_name ?? row.scope_type}</p><p>{Object.entries(row.reach).map(([module, reach]) => `${module}: ${reach}`).join(', ')}</p></div>)}</Card>}</div>;
}
