import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { IconShieldCheck } from '@tabler/icons-react';
import { adminApi, apiErrorMessage } from '@admin/api/adminApi';
import type { ScopedRoleAuditLog } from '@admin/model/admin';
import { Alert } from '@shared/ui/Alert'; import { Button } from '@shared/ui/Button'; import { Card } from '@shared/ui/Card'; import { Input } from '@shared/ui/Input'; import { AdminPageHeader as PageHeader } from '@admin/pages/access/AdminPageHeader';

const actions = ['role_assigned', 'role_revoked', 'role_updated', 'permission_granted', 'permission_revoked', 'access_denied'];
export function ScopedRoleAuditPage() {
  const { t } = useTranslation(); const [rows, setRows] = useState<ScopedRoleAuditLog[]>([]); const [action, setAction] = useState(''); const [userId, setUserId] = useState(''); const [page, setPage] = useState(1); const [meta, setMeta] = useState({ current_page: 1, last_page: 1, per_page: 25, total: 0 }); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = async (targetPage = page) => { setLoading(true); setError(null); try { const response = await adminApi.scopedRoleAudit.list({ action, user_id: userId, page: targetPage, per_page: 25 }); setRows(response.data); setMeta(response.meta); } catch (caught) { setError(apiErrorMessage(caught, t('common.error'))); } finally { setLoading(false); } };
  // Pagination owns automatic reload; filters are submitted explicitly.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(page); }, [page]);
  return <div className="space-y-6 p-6" data-testid="admin-protected-page"><PageHeader icon={IconShieldCheck} iconTone="admin" title={t('admin.scopedRolesAudit.title')} subtitle={t('admin.scopedRolesAudit.subtitle')} />{error && <Alert variant="danger">{error}</Alert>}<Card><div className="mb-4 grid gap-3 sm:grid-cols-[14rem_1fr_auto]"><label className="text-sm">{t('admin.scopedRolesAudit.fields.action')}<select aria-label={t('admin.scopedRolesAudit.fields.action')} className="mt-1 block w-full rounded-lg border p-2" value={action} onChange={(event) => setAction(event.target.value)}><option value="">{t('admin.scopedRolesAudit.filters.allActions')}</option>{actions.map((item) => <option key={item} value={item}>{t(`admin.scopedRolesAudit.actions.${item}`)}</option>)}</select></label><Input label={t('admin.scopedRolesAudit.filters.userId')} value={userId} onChange={(event) => setUserId(event.target.value)} /><Button variant="secondary" onClick={() => { if (page === 1) void load(1); else setPage(1); }}>{t('common.search')}</Button></div>{loading ? <p>{t('common.loading')}</p> : rows.length === 0 ? <p>{t('admin.scopedRolesAudit.empty')}</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-start">{t('admin.scopedRolesAudit.fields.user')}</th><th className="p-2 text-start">{t('admin.scopedRolesAudit.fields.action')}</th><th className="p-2 text-start">{t('admin.scopedRolesAudit.fields.targetUser')}</th><th className="p-2 text-start">{t('admin.scopedRolesAudit.fields.scope')}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b"><td className="p-2">{row.user?.name ?? '—'}</td><td className="p-2"><strong>{row.action}</strong><p>{row.description}</p></td><td className="p-2">{row.target_user?.name ?? '—'}</td><td className="p-2">{row.scope_type ?? '—'} / {row.role ?? '—'}</td></tr>)}</tbody></table></div>}<div className="mt-4 flex items-center justify-between"><span>{t('common.page')} {meta.current_page} / {meta.last_page}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>{t('common.previous')}</Button><Button size="sm" variant="secondary" disabled={page >= meta.last_page} onClick={() => setPage((current) => current + 1)}>{t('common.next')}</Button></div></div></Card></div>;
}
